name: "proxy"
mode: "dev"
version: "v0.0.1"
start_time: "20210724"
machine_id: 2
#machine_id 1 为client 提供local server  2位云服务器有公网ip

log:
  level: "debug"
  filename: "go_proxy.log"
  max_size: 200
  max_age: 30
  max_backups: 7
redis:
  host: "121.4.129.249"
  port: 63791
  password: "hello"
  db: 0
  pool_size: 100
serverport:
  host: "192.168.3.3"
  escServerPort: 221,23451
  locaServerPort: 22,2375
